//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BagisDetayResimTablo
    {
        public int BagisResimId { get; set; }
        public Nullable<int> BagisDetayTablo_BagisDetayId { get; set; }
        public string BagisResimUrl { get; set; }
    
        public virtual BagisDetayTablo BagisDetayTablo { get; set; }
    }
}
