//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BagisTablo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BagisTablo()
        {
            this.BagisDetayTablo = new HashSet<BagisDetayTablo>();
        }
    
        public int BagisId { get; set; }
        public string KullaniciBilgileriTablo_KullaniciGuId { get; set; }
        public Nullable<System.DateTime> EklenmeTarihi { get; set; }
        public Nullable<bool> OnaylandiMi { get; set; }
        public Nullable<System.DateTime> TahminiTeslimAlmaTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BagisDetayTablo> BagisDetayTablo { get; set; }
        public virtual KullaniciBilgileriTablo KullaniciBilgileriTablo { get; set; }
    }
}
