//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepoTablo
    {
        public int DepoEsyaId { get; set; }
        public Nullable<int> EsyaTablo_EsyaId { get; set; }
        public Nullable<int> SehirTablo_SehirId { get; set; }
        public Nullable<int> Adet { get; set; }
    
        public virtual EsyaTablo EsyaTablo { get; set; }
        public virtual SehirTablo SehirTablo { get; set; }
    }
}
