//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisardanIslemYapanTablo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DisardanIslemYapanTablo()
        {
            this.GeriBildirimTablo = new HashSet<GeriBildirimTablo>();
            this.IhtiyacSahibiTablo = new HashSet<IhtiyacSahibiTablo>();
            this.LogTablo = new HashSet<LogTablo>();
        }
    
        public int IslemYapanId { get; set; }
        public string IslemYapanAdi { get; set; }
        public string IslemYapanSoyadi { get; set; }
        public string IslemYapanTel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeriBildirimTablo> GeriBildirimTablo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IhtiyacSahibiTablo> IhtiyacSahibiTablo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogTablo> LogTablo { get; set; }
    }
}
