//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class IhtiyacSahibiVerilecekMaddiTablo
    {
        public int IhtiyacSahibiVerilecekMaddiId { get; set; }
        public Nullable<double> VerilecekMaddiYardim { get; set; }
        public Nullable<int> IhtiyacSahibiKontrolTablo_IhtiyacSahibiKontrolId { get; set; }
        public Nullable<System.DateTime> VerilmeGerceklesmeTarihi { get; set; }
    
        public virtual IhtiyacSahibiKontrolTablo IhtiyacSahibiKontrolTablo { get; set; }
    }
}
