//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class IhtiyacSahibiKontrolTablo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IhtiyacSahibiKontrolTablo()
        {
            this.IhtiyacSahibiVerileceklerTablo = new HashSet<IhtiyacSahibiVerileceklerTablo>();
        }
    
        public int IhtiyacSahibiKontrolId { get; set; }
        public string IhtiyacSahibiTablo_IhtiyacSahibiGuId { get; set; }
        public Nullable<bool> MuhtacMi { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<System.DateTime> IhtiyacSahibiKontrolYapilmaTarihi { get; set; }
        public Nullable<System.DateTime> İhtiyacSahibiTahminiTeslimTarihi { get; set; }
    
        public virtual IhtiyacSahibiTablo IhtiyacSahibiTablo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IhtiyacSahibiVerileceklerTablo> IhtiyacSahibiVerileceklerTablo { get; set; }
    }
}
