//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class IhtiyacSahibiTablo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IhtiyacSahibiTablo()
        {
            this.IhtiyacSahibiKontrolTablo = new HashSet<IhtiyacSahibiKontrolTablo>();
            this.IhtiyacSahibiVeKullaniciTablo = new HashSet<IhtiyacSahibiVeKullaniciTablo>();
        }
    
        public int IhtiyacSahibiId { get; set; }
        public string IhtiyacSahibiAdi { get; set; }
        public string IhtiyacSahibiSoyadi { get; set; }
        public string IhtiyacSahibiTelNo { get; set; }
        public string IhtiyacSahibiAdres { get; set; }
        public Nullable<int> SehirTablo_SehirId { get; set; }
        public string IhtiyacSahibiAciklama { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IhtiyacSahibiKontrolTablo> IhtiyacSahibiKontrolTablo { get; set; }
        public virtual SehirTablo SehirTablo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IhtiyacSahibiVeKullaniciTablo> IhtiyacSahibiVeKullaniciTablo { get; set; }
    }
}
