//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class IhtiyacSahibiTablo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IhtiyacSahibiTablo()
        {
            this.IhtiyacSahibiKontrolTablo = new HashSet<IhtiyacSahibiKontrolTablo>();
        }
    
        public string IhtıyacSahibiGuId { get; set; }
        public string IhtıyacSahibiAdi { get; set; }
        public string İhtiyacSahibiSoyadi { get; set; }
        public string İhtiyacSahibiTelNo { get; set; }
        public string IhtiyacSahibiAdres { get; set; }
        public Nullable<int> SehirTablo_SehirId { get; set; }
        public Nullable<int> DisardanIslemYapanTablo_IslemYapanId { get; set; }
    
        public virtual DisardanIslemYapanTablo DisardanIslemYapanTablo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IhtiyacSahibiKontrolTablo> IhtiyacSahibiKontrolTablo { get; set; }
        public virtual SehirTablo SehirTablo { get; set; }
    }
}
