//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class KasaTablo
    {
        public int KasaId { get; set; }
        public Nullable<decimal> Miktar { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Aciklama { get; set; }
        public string KullaniciBilgleriTablo_KullaniciGuId { get; set; }
        public Nullable<int> SehirTablo_SehirId { get; set; }
        public Nullable<int> DisardanIslemYapanTablo_IslemYapanId { get; set; }
    
        public virtual KullaniciBilgileriTablo KullaniciBilgileriTablo { get; set; }
        public virtual SehirTablo SehirTablo { get; set; }
    }
}
