//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogTablo
    {
        public int LogId { get; set; }
        public string KullaniciBilgileriTablo_KullaniciGuId { get; set; }
        public string YapılanIslem { get; set; }
        public Nullable<int> DisardanIslemYapanTablo_IslemYapanId { get; set; }
    
        public virtual DisardanIslemYapanTablo DisardanIslemYapanTablo { get; set; }
        public virtual KullaniciBilgileriTablo KullaniciBilgileriTablo { get; set; }
    }
}
