//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class YetkiTablo
    {
        public int YetkiId { get; set; }
        public string KullaniciBilgileriTablo_KullaniciGuId { get; set; }
        public Nullable<int> RotaTablo_RotaId { get; set; }
        public Nullable<bool> GirebilirMi { get; set; }
    
        public virtual KullaniciBilgileriTablo KullaniciBilgileriTablo { get; set; }
        public virtual RotaTablo RotaTablo { get; set; }
    }
}
